
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: controller-manager
  namespace: system
spec:
  endpoints:
  - bearerTokenFile: "/var/run/secrets/kubernetes.io/serviceaccount/token"
    interval: 30s
    targetPort: 8080
    path: /metrics
    scheme: https
    tlsConfig:
      # The CA file used by Prometheus to verify the server's certificate.
      # It's the cluster's CA bundle from the service CA operator.
      caFile: /etc/prometheus/configmaps/serving-certs-ca-bundle/service-ca.crt
      # The name of the server (CN) in the server's certificate.
      serverName: numaresources-controller-manager-metrics-service.numaresources.svc
      insecureSkipVerify: false
  selector:
    matchLabels:
      control-plane: controller-manager
