apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: rte-metrics-service-cert
  labels:
    name: resource-topology
  name: numaresources-rte-metrics-service
spec:
  ports:
  - name: metrics-port
    port: 2112
    protocol: TCP
    targetPort: metrics-port
  selector:
    name: resource-topology
