name: CI Linter with golangci-lint

on:
  pull_request:
    branches:
      - main
      - "release-4.1[8]"
  push:
    branches: 
      - main

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up golang
      uses: actions/setup-go@v5
      with:
        go-version: 1.23.3

    - name: Run Linter
      run: make golangci-lint
